apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-api
  namespace: gym-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-api
  template:
    metadata:
      labels:
        app: gym-api
    spec:
      containers:
      - name: gym-api
        image: ghcr.io/s3nthilg0pal/gym-api:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gym-secret
              key: DATABASE_URL
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: gym-secret
              key: API_KEY
        - name: PORT
          value: "8080"