apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealedsecret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/s3nthilg0pal/gym-api
    newTag: main