---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gym-ollama-secret
  namespace: gym-api
spec:
  encryptedData:
    OLLAMA_URL: AgAnnnQgb/Zu6VeFzQNO+/lEGL/eMREjrW/kawHGWiiBcs3iZCtgZFrnk+kNrBRHKdod3lOh1Y/8gdvjB7vrzwhCuv5FGnimTN0T4wpZCZPniYkOaRvDSVmsnMG/HioV0Z69U37gvkx4nmca+lHVNPjXldmiG6M6htmcw14L1w5kLmNc6A/n1uUnO5eJ+aUDvJV82DQ74Y7YTGctJbnaEX8fPD7gWA+LtqV79SL+bzRLk4ppEZ7oT4/K8gVcC9Z4lQeQc5pc+kHd2/3kg5+6i499zGYXarSgx5vlXQ/aEBXTzpISvvEAuHsqFbrfzOobecFHgZlEsB4uGxFb2/9SiMy8rhwivj5Zp2rIULbzGn1icDHxobue67tg2ZPVojLnmjI1Ca5181nGU9wOKVtioUUPnKrOOY71vFa3sg2Zo81i5PWxzddm/IBeBXEeR6Ho3UxrKCOJtBXdMyhvpuouYZquQjZIoKxkY6XKuk7Z5/h6RF5us92A6Q7luuSvrrsV55hToCjLl8GddrQKcagPsT255ABb3nT/lWGWa9QfMcdysOoYk2JwjIY2bP0ZzD5tniLknBtPzNF6scgFY25U/jaDabAvVagFkYtgkVC+FR5OTgHJYWG4dkCN8VKdzizuy7vTPNA/y6MDUqa3IZzMsZhGPKcOyWc/51TXsSVxM7V9qZT/vEx/Qn0SxdOdJ4gL3bUWtWmFkJ/FFR1CYLsVcwb6qIgdPyK3pRj8Jg==
  template:
    metadata:
      name: gym-ollama-secret
      namespace: gym-api
